// ── AI-DTL specification registry
// One place for codes, rules and texts. Editor, explanation page and tests read from here.
// SPEC['0.4'] is frozen (texts as published in June 2026). SPEC['0.5'] follows the
// revision plan, Annex A; ENABLE_M switches the provisional level M (decision E3).

// Canonical base URL of this copy of the site; shared links always point here.
// Release candidate: links point to rc/label/?v=0.5… until 0.5 is released (Phase 7).
const SITE_BASE = 'https://joshuadohmen-sketch.github.io/AIDL/rc/';

// Provisional (E3): level M "existing work modified". false → all "[ohne M]" texts apply.
const ENABLE_M = true;

function deepFreeze(o) {
  Object.values(o).forEach(v => { if (v && typeof v === 'object' && !Object.isFrozen(v)) deepFreeze(v); });
  return Object.freeze(o);
}

// ── Version 0.4 (frozen) ─────────────────────────────────────────────────────
const SPEC_04 = {
  version: '0.4',
  // rank: stamm – higher is stronger; host – lower is less protected
  codes: {
    stamm:  { N: 0, A: 1, S: 2, G: 3 },
    host:   { 'H:C!': 0, 'H:C': 1, 'H:I': 2, 'H:L': 3 },
    review: { 'R:H': 0, 'R:M': 1, 'R:HM': 2, 'R:N': 3 },
    acc:    { 'Acc:I': 0, 'Acc:O': 1, 'Acc:N': 2 },
  },
  order: {
    stamm:  ['N', 'A', 'S', 'G'],
    host:   ['H:L', 'H:I', 'H:C', 'H:C!'],
    review: ['R:H', 'R:M', 'R:HM', 'R:N'],
    acc:    ['Acc:I', 'Acc:O', 'Acc:N'],
  },
  rules: {
    noAiAcc: ['Acc:I', 'Acc:O'],          // what the editor can produce
    noAiAccLegacy: ['Acc:I', 'Acc:O', 'Acc:N'], // what old links may contain
    toolRequired: false,
    dateRequired: false,
    toolDisplayMax: 200,
  },
  warnings: [
    { id: 'hcx',    trigger: 'H:C!',      when: s => s.host === 'H:C!' },
    { id: 'g_rn',   trigger: 'G + R:N',   when: s => s.stamm === 'G' && s.review === 'R:N' },
    { id: 'g_accn', trigger: 'G + Acc:N', when: s => s.stamm === 'G' && s.acc === 'Acc:N' },
  ],
  i18n: {
    de: {
      ui: {
        hero_title: 'AI Disclosure & Transparency Label Generator',
        hero_desc: 'Generieren Sie ein valides AI-DTL 0.4 für Ihr Artefakt.',
        step: 'Schritt 1', step2: 'Schritt 2', step3: 'Schritt 3', step4: 'Schritt 4', step5: 'Schritt 5',
        s1_title: 'Ausmaß der KI-Nutzung',         s1_sub: 'Wie stark war KI an der Entstehung des Artefakts beteiligt?',
        s1_hint: 'Mehrfachauswahl möglich – bei mehreren Stufen zählt die höchste tatsächliche Wirkung.',
        s2_title: 'Hosting-Kontext',                s2_sub: 'Wo lief das KI-System? Relevant für Datenschutz und DFG-Konformität.',
        s2_hint: 'Mehrfachauswahl möglich – bei mehreren Hosts zählt der am wenigsten geschützte.',
        s3_title: 'Prüfung der KI-Ausgaben',        s3_sub: 'Wurden die KI-Ausgaben geprüft, bevor sie übernommen wurden?',
        s4_title: 'Accountability – Verantwortung', s4_sub: 'Wer steht für das Artefakt ein?',
        s5_title: 'Tool-Angabe',                    s5_sub: 'Welches KI-System wurde verwendet? Name, Version und Monat der Nutzung.',
        tool_ph: 'z.B. Claude Opus 4.6', tool_aria: 'KI-Tool Name',
        btn_add_tool: '+ weiteres Tool', remove_tool_aria: 'Tool entfernen',
        warn_when_title: 'Wann warnt der Generator?',
        result_label: 'Ihr AI-DTL-Label',
        result_ph: 'Bitte alle Felder ausfüllen …',
        btn_text: 'Text kopieren', btn_meta: 'HTML <meta>', btn_md: 'Markdown',
        btn_latex: 'LaTeX', btn_link: 'Link kopieren',
        btn_badge: 'Badge ↓ SVG', btn_png: 'Badge ↓ PNG',
        no_ai_hint: 'Bei N entfallen Host, Review und Tool. Bitte Accountability auswählen.',
        alert_incomplete: 'Bitte zuerst alle Felder ausfüllen.',
        month_ph: 'Monat', year_ph: 'Jahr',
      },
      months: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
      opt: {
        N:      { lbl: 'No AI',            dsc: 'Keine KI-Beteiligung am Artefakt' },
        A:      { lbl: 'Assistive',        dsc: 'Sprachpolitur, Rechtschreibkorrektur, Übersetzung' },
        S:      { lbl: 'Supportive',       dsc: 'Brainstorming, Gliederung, Recherche-Hilfe' },
        G:      { lbl: 'Generative',       dsc: 'Substantielle Text-, Code- oder Datengenerierung' },
        'H:L':  { lbl: 'Local',            dsc: 'Lokal ausgeführt, keine Datenübertragung (z.B. Ollama)' },
        'H:I':  { lbl: 'Institutional',    dsc: 'Hochschul- oder Behördeninstanz mit interner AVV' },
        'H:C':  { lbl: 'Cloud w/ DPA',     dsc: 'Kommerzieller Cloud-Dienst mit Auftragsverarbeitungsvertrag' },
        'H:C!': { lbl: 'Cloud w/o DPA',    dsc: 'Ohne AVV – in vielen Kontexten unzulässig' },
        'R:H':  { lbl: 'Human reviewed',   dsc: 'Menschliche Prüfung der KI-Ausgaben' },
        'R:M':  { lbl: 'Machine reviewed', dsc: 'Automatisierte Prüfung (Linter, Faktenchecker)' },
        'R:HM': { lbl: 'Both',             dsc: 'Mensch und Maschine haben geprüft' },
        'R:N':  { lbl: 'None',             dsc: 'Keine Prüfung – Ausgabe unverändert übernommen' },
        'Acc:I': { lbl: 'Individual',      dsc: 'Benennbare Einzelperson (z.B. Autor:in mit ORCID)' },
        'Acc:O': { lbl: 'Organizational',  dsc: 'Organisation übernimmt Verantwortung' },
        'Acc:N': { lbl: 'None claimed',    dsc: 'Rein agentischer Raum – kein Mensch steht ein' },
      },
      exp: {
        N: 'Keine KI-Beteiligung', A: 'Assistive Nutzung', S: 'Supportive Nutzung', G: 'Generative Nutzung',
        'H:L': 'lokal gehostet', 'H:I': 'institutionell gehostet', 'H:C': 'Cloud mit AVV', 'H:C!': '⚠ Cloud ohne AVV',
        'R:H': 'menschlich geprüft', 'R:M': 'maschinell geprüft', 'R:HM': 'Mensch & Maschine', 'R:N': '⚠ nicht geprüft',
        'Acc:I': 'Einzelperson verantwortlich', 'Acc:O': 'Organisation verantwortlich', 'Acc:N': '⚠ keine Accountability',
      },
      warn: {
        hcx:    'Cloud-Nutzung ohne Auftragsverarbeitungsvertrag (AVV): Wenn Sie personenbezogene oder vertrauliche Daten eingegeben haben, ist das in der Regel nicht zulässig.',
        g_rn:   'Generative KI-Ausgaben wurden ungeprüft übernommen. Prüfen Sie Fakten und Quellen vor der Veröffentlichung.',
        g_accn: 'Für generative KI-Inhalte ist keine Verantwortung angegeben. Passt „Organizational“?',
      },
      page: {
        page_sub: 'Dieses Artefakt trägt folgendes AI-DTL-Label:',
        create_own: 'Eigenes Label erstellen',
        create_sub: 'Verwenden Sie den AI-DTL Generator, um ein Label für Ihr Artefakt zu erzeugen.',
        invalid: 'Ungültiges Label',
        invalid_sub: 'Die URL enthält kein gültiges AI-DTL-Label. Bitte verwenden Sie den Generator.',
        tool_used: 'Verwendetes KI-System',
        legacy_n_accn: 'Diese Kombination ist seit Version 0.4 nicht mehr vorgesehen.',
      },
      dims: {
        N:      { title: 'Keine KI-Beteiligung',         desc: 'Dieses Artefakt wurde vollständig ohne KI-Unterstützung erstellt.' },
        A:      { title: 'Assistive KI-Nutzung',         desc: 'KI wurde ausschließlich für Hilfsfunktionen wie Sprachpolitur, Rechtschreibkorrektur oder Übersetzung eingesetzt.' },
        S:      { title: 'Supportive KI-Nutzung',        desc: 'KI unterstützte beim Brainstorming, bei der Gliederung oder bei der Recherche. Die inhaltliche Gestaltung lag beim Menschen.' },
        G:      { title: 'Generative KI-Nutzung',        desc: 'KI hat substantielle Teile dieses Artefakts erzeugt – Text, Code oder Daten wurden maßgeblich von KI generiert.' },
        'H:L':  { title: 'Lokales Hosting',              desc: 'Das KI-System lief lokal auf dem eigenen Rechner. Es wurden keine Daten an externe Server übertragen.' },
        'H:I':  { title: 'Institutionelles Hosting',     desc: 'Das KI-System wurde auf einer Hochschul- oder Behördeninstanz betrieben, mit interner Auftragsverarbeitung (AVV).' },
        'H:C':  { title: 'Cloud-Hosting mit AVV',        desc: 'Ein kommerzieller Cloud-Dienst wurde genutzt, für den ein Auftragsverarbeitungsvertrag (AVV/DPA) besteht.' },
        'H:C!': { title: 'Cloud-Hosting ohne AVV',       desc: 'Ein kommerzieller Cloud-Dienst wurde ohne Auftragsverarbeitungsvertrag genutzt. Dies ist in vielen institutionellen Kontexten unzulässig.' },
        'R:H':  { title: 'Menschlich geprüft',           desc: 'Die KI-Ausgaben wurden von einem Menschen inhaltlich geprüft, bevor sie übernommen wurden.' },
        'R:M':  { title: 'Maschinell geprüft',           desc: 'Die KI-Ausgaben wurden automatisiert geprüft (z.B. durch Linter, Faktenchecker oder Validierungstools).' },
        'R:HM': { title: 'Mensch & Maschine geprüft',    desc: 'Sowohl ein Mensch als auch automatisierte Systeme haben die KI-Ausgaben geprüft.' },
        'R:N':  { title: 'Keine Prüfung',                desc: 'Die KI-Ausgaben wurden ungeprüft und unverändert übernommen. Dies birgt ein erhöhtes Risiko für Fehler und Halluzinationen.' },
        'Acc:I': { title: 'Individuelle Verantwortung',  desc: 'Eine benennbare Einzelperson (z.B. Autor:in mit ORCID) steht für dieses Artefakt ein.' },
        'Acc:O': { title: 'Organisatorische Verantwortung', desc: 'Eine Organisation übernimmt die Verantwortung für dieses Artefakt.' },
        'Acc:N': { title: 'Keine Verantwortung deklariert', desc: 'Niemand hat die Verantwortung für dieses Artefakt übernommen. Es handelt sich um einen rein agentischen Kontext.' },
      },
    },
    en: {
      ui: {
        hero_title: 'AI Disclosure & Transparency Label Generator',
        hero_desc: 'Generate a valid AI-DTL 0.4 for your artefact.',
        step: 'Step 1', step2: 'Step 2', step3: 'Step 3', step4: 'Step 4', step5: 'Step 5',
        s1_title: 'Extent of AI Use',    s1_sub: 'How deeply was AI involved in creating this artefact?',
        s1_hint: 'Multiple selection possible – when multiple levels apply, the highest effective level is coded.',
        s2_title: 'Hosting Context',     s2_sub: 'Where did the AI run? Relevant for data protection and DFG compliance.',
        s2_hint: 'Multiple selection possible – when multiple hosts apply, the least protected is coded.',
        s3_title: 'Review of AI Output', s3_sub: 'Was the AI output reviewed before being adopted?',
        s4_title: 'Accountability',      s4_sub: 'Who is accountable for this artefact?',
        s5_title: 'Tool Declaration',    s5_sub: 'Which AI system was used? Provide name, version, and month of use.',
        tool_ph: 'e.g. Claude Opus 4.6', tool_aria: 'AI tool name',
        btn_add_tool: '+ add tool', remove_tool_aria: 'Remove tool',
        warn_when_title: 'When does the generator warn?',
        result_label: 'Your AI-DTL Label',
        result_ph: 'Please complete all fields …',
        btn_text: 'Copy text', btn_meta: 'HTML <meta>', btn_md: 'Markdown',
        btn_latex: 'LaTeX', btn_link: 'Copy link',
        btn_badge: 'Badge ↓ SVG', btn_png: 'Badge ↓ PNG',
        no_ai_hint: 'For N, Host, Review and Tool are omitted. Please select Accountability.',
        alert_incomplete: 'Please complete all fields first.',
        month_ph: 'Month', year_ph: 'Year',
      },
      months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      opt: {
        N:      { lbl: 'No AI',            dsc: 'No AI involvement in the artefact' },
        A:      { lbl: 'Assistive',        dsc: 'Language polishing, spell-check, translation' },
        S:      { lbl: 'Supportive',       dsc: 'Brainstorming, structuring, research support' },
        G:      { lbl: 'Generative',       dsc: 'Substantial text, code, or data generation by AI' },
        'H:L':  { lbl: 'Local',            dsc: 'Locally executed, no data transfer (e.g. Ollama)' },
        'H:I':  { lbl: 'Institutional',    dsc: 'University or authority instance with internal DPA' },
        'H:C':  { lbl: 'Cloud w/ DPA',     dsc: 'Commercial cloud service with data processing agreement' },
        'H:C!': { lbl: 'Cloud w/o DPA',    dsc: 'No DPA – unlawful in many contexts' },
        'R:H':  { lbl: 'Human reviewed',   dsc: 'Human review of AI output' },
        'R:M':  { lbl: 'Machine reviewed', dsc: 'Automated review (linter, fact-checker)' },
        'R:HM': { lbl: 'Both',             dsc: 'Human and machine reviewed' },
        'R:N':  { lbl: 'None',             dsc: 'No review – AI output adopted unchanged' },
        'Acc:I': { lbl: 'Individual',      dsc: 'Named individual (e.g. author with ORCID)' },
        'Acc:O': { lbl: 'Organizational',  dsc: 'Organization takes responsibility' },
        'Acc:N': { lbl: 'None claimed',    dsc: 'Purely agentic context – no human stands behind this' },
      },
      exp: {
        N: 'No AI involvement', A: 'Assistive use', S: 'Supportive use', G: 'Generative use',
        'H:L': 'locally hosted', 'H:I': 'institutionally hosted', 'H:C': 'cloud with DPA', 'H:C!': '⚠ cloud without DPA',
        'R:H': 'human reviewed', 'R:M': 'machine reviewed', 'R:HM': 'human & machine', 'R:N': '⚠ not reviewed',
        'Acc:I': 'individual accountable', 'Acc:O': 'organization accountable', 'Acc:N': '⚠ no accountability',
      },
      warn: {
        hcx:    'Cloud use without a data processing agreement (DPA): if you entered personal or confidential data, this is usually not permitted.',
        g_rn:   'Generative AI output was adopted without review. Check facts and sources before publishing.',
        g_accn: 'No accountability is declared for generative AI content. Would “Organizational” fit?',
      },
      page: {
        page_sub: 'This artefact carries the following AI-DTL label:',
        create_own: 'Create your own label',
        create_sub: 'Use the AI-DTL Generator to create a label for your artefact.',
        invalid: 'Invalid label',
        invalid_sub: 'This URL does not contain a valid AI-DTL label. Please use the generator.',
        tool_used: 'AI system used',
        legacy_n_accn: 'This combination is no longer intended since version 0.4.',
      },
      dims: {
        N:      { title: 'No AI involvement',            desc: 'This artefact was created entirely without AI assistance.' },
        A:      { title: 'Assistive AI use',             desc: 'AI was used only for auxiliary functions such as language polishing, spell-checking, or translation.' },
        S:      { title: 'Supportive AI use',            desc: 'AI assisted with brainstorming, structuring, or research. The substantive content was created by a human.' },
        G:      { title: 'Generative AI use',            desc: 'AI generated substantial parts of this artefact – text, code, or data were significantly produced by AI.' },
        'H:L':  { title: 'Local hosting',                desc: 'The AI system ran locally on the user\'s own machine. No data was transmitted to external servers.' },
        'H:I':  { title: 'Institutional hosting',        desc: 'The AI system was operated on a university or authority instance with an internal data processing agreement.' },
        'H:C':  { title: 'Cloud hosting with DPA',       desc: 'A commercial cloud service was used under a data processing agreement (DPA).' },
        'H:C!': { title: 'Cloud hosting without DPA',    desc: 'A commercial cloud service was used without a data processing agreement. This may be unlawful in many institutional contexts.' },
        'R:H':  { title: 'Human reviewed',               desc: 'The AI outputs were reviewed by a human before being adopted.' },
        'R:M':  { title: 'Machine reviewed',             desc: 'The AI outputs were checked by automated tools (e.g. linters, fact-checkers, or validation tools).' },
        'R:HM': { title: 'Human & machine reviewed',     desc: 'Both a human and automated systems reviewed the AI outputs.' },
        'R:N':  { title: 'No review',                    desc: 'The AI outputs were adopted without any review. This carries an elevated risk of errors and hallucinations.' },
        'Acc:I': { title: 'Individual accountability',   desc: 'A named individual (e.g. author with ORCID) is accountable for this artefact.' },
        'Acc:O': { title: 'Organizational accountability', desc: 'An organization takes responsibility for this artefact.' },
        'Acc:N': { title: 'No accountability claimed',   desc: 'Nobody has claimed responsibility for this artefact. This is a purely agentic context.' },
      },
    },
  },
};

// ── Version 0.5 (texts: revision plan Annex A/B, revised after review 09.10.2026) ──
// Option titles follow the letter of the code: German word with the same initial,
// otherwise German word plus the English key word in brackets.
function buildSpec05(enableM) {
  const stammOrder = enableM ? ['N', 'A', 'S', 'M', 'G'] : ['N', 'A', 'S', 'G'];
  const stammRank = {};
  stammOrder.forEach((c, i) => { stammRank[c] = i; });

  const mg = s => s.stamm === 'M' || s.stamm === 'G';

  const de = {
    ui: {
      title: 'AI-DTL Generator',
      subtitle: 'Kennzeichnung der KI-Nutzung in fünf Schritten',
      header_version: 'v 0.5 (Vorschau)',
      footer_draft: 'AI-DTL Working Draft 0.5 (Vorschau)',
      skip: 'Zum Editor springen',
      step: 'Schritt',
      doi: 'DOI folgt (Zenodo)',
      downloaded: 'Heruntergeladen',
      multi: 'Mehrere Antworten möglich',
      single: 'Eine Antwort',
      restart: 'Neu beginnen',
      examples: 'Beispiele ansehen',
      more_levels: 'Mehr zu den Stufen',
      yes: 'Ja', no: 'Nein', dont_know: 'Weiß nicht',
      result_title: 'Ihr AI-DTL',
      result_intro: 'Ihr Label besteht aus einem Satz für Lesende und einem Code.',
      result_placeholder: 'Ihr Label erscheint hier, sobald alle Schritte ausgefüllt sind.',
      copied: 'Kopiert',
      remove_tool: 'Werkzeug entfernen',
      tool_name: 'Werkzeug',
      month: 'Monat', year: 'Jahr',
      when_title: 'Wann gibt der Editor Hinweise?',
      btn_text: 'Text', btn_html: 'HTML-Baustein', btn_md: 'Markdown', btn_latex: 'LaTeX',
      btn_link: 'Link', btn_speech: 'Sprechtext', btn_svg: 'Badge ↓ SVG', btn_png: 'Badge ↓ PNG',
      study_banner: 'Studienmodus – Ihre Eingaben werden nicht gespeichert',
      study_case: 'Fall',
      study_copy: 'Ergebnis für den Fragebogen kopieren',
      footer_test: 'Version 0.5 wird gerade mit Nutzer:innen getestet – Feedback willkommen',
      legacy_loaded: 'Dieses Label wurde mit Version 0.4 erstellt. Bitte prüfen Sie die Angaben nach den Regeln von 0.5.',
      part_label: 'Nur ein einzelnes Bild, Video oder Tonstück ist mit KI erzeugt oder verändert? Empfehlung: ein eigenes Label direkt an diesem Element und ein Label für den Rest des Werks.',
    },
    months: SPEC_04.i18n.de.months,
    steps: {
      stamm:  { title: 'Ausmaß – Was hat die KI gemacht?', sub: 'Im Label zählt die stärkste Stufe.' },
      tools:  { title: 'Tool – Welche KI-Werkzeuge haben Sie genutzt?', sub: 'Dienst oder Modell und Monat der letzten Nutzung.' },
      host:   { title: 'Hosting (H) – Wo lief die KI?', sub: 'Entscheidend ist, ob Ihre Eingaben Ihre Organisation verlassen haben.' },
      review: { title: 'Review (R) – Wurden die KI-Ausgaben geprüft?', sub: '' },
      acc:    { title: 'Accountability (Acc) – Wer steht für das Werk ein?', sub: 'Maschinen können prüfen, aber nicht einstehen.' },
    },
    opt: {
      N: { lbl: 'Keine KI (No AI)', dsc: 'Das Werk ist ohne KI entstanden.' },
      A: { lbl: 'Assistiv', dsc: 'KI hat assistiert; Inhalt und Aussage stammen von Ihnen.' },
      S: { lbl: 'Supportiv', dsc: 'KI hat Ihre Arbeit unterstützt; im Werk steht kein KI-Inhalt.' },
      M: { lbl: 'Modifiziert', dsc: 'KI hat Ihr vorhandenes Werk verändert.' },
      G: enableM
        ? { lbl: 'Generativ', dsc: 'KI hat Inhalte erzeugt, die im Werk stehen.' }
        : { lbl: 'Generativ', dsc: 'KI hat Inhalte erzeugt, die im Werk stehen, oder Ihr vorhandenes Werk verändert.' },
      'H:L':  { lbl: 'Lokal', dsc: 'Auf Ihrem Gerät oder auf Servern Ihrer eigenen Organisation – die Eingaben verlassen Ihre Organisation nicht.' },
      'H:I':  { lbl: 'Institutionell', dsc: 'Bei einer vertrauenswürdigen öffentlichen Einrichtung außerhalb Ihrer Organisation, z. B. einem wissenschaftlichen Rechenzentrum.' },
      'H:C':  { lbl: 'Kommerziell mit Vertrag (Commercial)', dsc: 'Ein Unternehmen, das Ihre Eingaben laut Vertrag nicht für eigene Zwecke nutzen darf.' },
      'H:C!': { lbl: 'Kommerziell ohne Vertrag (Commercial)', dsc: 'Ein Unternehmen ohne solchen Vertrag, z. B. privates oder kostenloses Konto.' },
      'R:H':  { lbl: 'Mensch (Human)', dsc: 'Ein Mensch hat den Inhalt geprüft.' },
      'R:HM': { lbl: 'Mensch und Maschine (Human + Machine)', dsc: 'Ein Mensch und Software haben geprüft.' },
      'R:M':  { lbl: 'Maschine (Machine)', dsc: 'Nur Software hat geprüft.' },
      'R:N':  { lbl: 'Keine Prüfung (None)', dsc: 'Die KI-Ausgaben wurden nicht geprüft.' },
      'Acc:I': { lbl: 'Person (Individual)', dsc: 'Eine benannte Person steht ein.' },
      'Acc:O': { lbl: 'Organisation', dsc: 'Eine Organisation steht ein.' },
      'Acc:N': { lbl: 'Niemand (None)', dsc: 'Niemand steht ein.' },
    },
    cumul: {
      stamm: 'Im Label: {X} – bei mehreren Stufen zählt die stärkste.',
      host: 'Im Label: {X} – bei mehreren zählt der am wenigsten geschützte Ort.',
    },
    helper: {
      title: 'Unsicher? Ein paar Fragen',
      q1: 'Steht im fertigen Werk etwas, das die KI erzeugt oder verändert hat – und sei es nur eine Korrektur?',
      q1b: 'Hat KI Ihnen bei Ideen, Gliederung, Recherche oder Fehlersuche geholfen?',
      q2: 'Hat die KI nur Fehler korrigiert oder einzelne Sätze geglättet, eigene Texte übersetzt oder transkribiert oder die Bildqualität verbessert?',
      q2b: 'Hat KI außerdem bei Ideen, Gliederung, Recherche oder Fehlersuche geholfen?',
      q3: 'Ist Ihr eigenes Werk erhalten geblieben und wurde von der KI über einzelne Sätze hinaus verändert (z. B. Absätze umformuliert, Code geändert, ein Objekt aus einem Foto entfernt)? → M. Oder hat die KI etwas Neues hervorgebracht, auch aus Ihrem Material (z. B. Zusammenfassung, Text aus Stichpunkten, neue Funktion, Bild, synthetische Stimme)? → G.',
      q3_both: 'Beides',
      both_note: 'Kommt beides vor (Verändertes und neu Erzeugtes), gilt G.',
      result: 'Vorschlag: {X}',
      apply: 'Übernehmen',
      again: 'Noch einmal',
    },
    host_helper: {
      title: 'Unsicher?',
      left: 'Haben Ihre Eingaben Ihre Organisation verlassen?',
      to: 'An wen?',
      to_public: 'Öffentliche Einrichtung',
      to_company: 'Unternehmen',
      contract: 'Gibt es einen Vertrag, der die Nutzung Ihrer Eingaben ausschließt?',
    },
    purpose: {
      label: 'Wofür wurde KI eingesetzt? (optional)',
      ph: 'z. B. Übersetzung der Zusammenfassung, Bild auf Folie 12',
      help: 'Erscheint nur im Satz, nicht im Code.',
    },
    no_ai_hint: 'Ohne KI entfallen die Schritte Tool, Hosting und Review.',
    tools: {
      ph: 'z. B. Ollama/Llama 4',
      date: 'Monat der letzten Nutzung',
      add: '+ weiteres Werkzeug',
      generic: 'Tipp: Ergänzen Sie hinter dem Schrägstrich Modell oder Version, z. B. „ChatGPT/GPT-5“.',
      host_suggest: 'Vorschlag für den nächsten Schritt: {host}, weil Sie „{service}“ gewählt haben. Bitte prüfen.',
      bad_chars: 'Die Zeichen ; ( ) , | sind im Werkzeugnamen nicht möglich.',
    },
    host_hint: 'Eine Lizenz Ihrer Organisation heißt nicht, dass der Dienst auf deren Servern läuft. Meist läuft er beim Anbieter (Kommerziell mit Vertrag).',
    review_hint_as: 'Bei Assistiv oder Supportiv: Haben Sie die Vorschläge der KI bewusst angenommen oder verworfen? Dann „Mensch“.',
    resp: {
      label: 'Wer steht dafür ein? (optional)',
      ph: 'z. B. Maria Muster oder Redaktion Musterverlag',
      help: 'Name oder Organisation. Eine ORCID oder ROR-ID wird verlinkt. Erscheint nur im Satz.',
    },
    sentence: {
      stamm: {
        N: 'Ohne KI erstellt.',
        A: 'Inhalt von Menschen; KI hat assistiert.',
        S: 'Inhalt von Menschen; KI hat die Arbeit unterstützt.',
        M: 'Enthält mit KI veränderte Inhalte.',
        G: 'Enthält mit KI erzeugte Inhalte.',
      },
      purpose: 'KI eingesetzt für: {p}.',
      reviewAS: {
        'R:H': 'KI-Vorschläge von einem Menschen geprüft.',
        'R:HM': 'KI-Vorschläge von einem Menschen und automatisch geprüft.',
        'R:M': 'KI-Vorschläge nur automatisch geprüft.',
        'R:N': 'KI-Vorschläge ohne Prüfung genutzt.',
      },
      reviewMG: {
        'R:H': 'KI-Ausgaben von einem Menschen inhaltlich geprüft.',
        'R:HM': 'KI-Ausgaben von einem Menschen inhaltlich und zusätzlich automatisch geprüft.',
        'R:M': 'KI-Ausgaben nur automatisch geprüft, nicht von einem Menschen.',
        'R:N': 'KI-Ausgaben nicht geprüft.',
      },
      resp: 'Verantwortlich: {rp}.',
      acc: {
        'Acc:I': 'Eine Person übernimmt die Verantwortung.',
        'Acc:O': 'Eine Organisation übernimmt die Verantwortung.',
        'Acc:N': 'Niemand übernimmt die Verantwortung.',
      },
    },
    speech: {
      prefix: 'Hinweis:',
      stamm: {
        N: 'Dieser Inhalt wurde ohne KI erstellt.',
        A: 'Dieser Inhalt stammt von Menschen; KI hat assistiert.',
        S: 'Dieser Inhalt stammt von Menschen; KI hat die Arbeit unterstützt.',
        M: 'Dieser Inhalt wurde mit KI verändert.',
        G: 'Dieser Inhalt wurde mit KI erzeugt.',
      },
      review: {
        'R:H': 'Ein Mensch hat ihn geprüft.',
        'R:HM': 'Ein Mensch und eine Software haben ihn geprüft.',
        'R:M': 'Er wurde nur automatisch geprüft.',
        'R:N': 'Er wurde nicht geprüft.',
      },
    },
    warn: {
      hcx: 'Sie haben einen Dienst ohne Vertrag genutzt. Haben Sie personenbezogene oder vertrauliche Daten eingegeben? Dann ist das in der Regel nicht zulässig.',
      mg_rn: 'KI-Inhalte wurden ungeprüft übernommen. Prüfen Sie Fakten und Quellen vor der Veröffentlichung.',
      mg_rm: 'Eine nur automatische Prüfung ersetzt keine menschliche Prüfung.',
      accn: 'Niemand übernimmt Verantwortung. Passt eher „Organisation“?',
    },
    art50: {
      title: 'Muss zusätzlich das EU-Kennzeichen an den Inhalt?',
      question: 'Wird der Inhalt veröffentlicht und ist er (a) ein realistisch wirkendes Bild, Ton oder Video, das echte Personen, Orte oder Ereignisse zeigt oder verändert, oder (b) ein Text, der die Öffentlichkeit über Angelegenheiten von öffentlichem Interesse informieren soll, wenn ihn kein Mensch inhaltlich geprüft hat oder keine Person oder Einrichtung öffentlich die redaktionelle Verantwortung übernimmt?',
      yes: 'Dann verlangt Art. 50 der KI-Verordnung einen sichtbaren Hinweis direkt am Inhalt, spätestens beim ersten Kontakt – bei Video am Anfang, bei Ton gesprochen. Dafür gibt es die EU-Kennzeichen. Das AI-DTL kann als zweite Ebene dahinter stehen. Passend wäre vermutlich: {icon}. Dies ist keine Rechtsberatung.',
      link: 'Zu den EU-Kennzeichen',
      no: 'Dann ist das AI-DTL eine freiwillige Angabe.',
      unknown: 'Im Zweifel lieber zusätzlich kennzeichnen. Fragen Sie Ihre zuständige Stelle.',
      icons: { partial: 'Partially AI-Modified', full: 'Fully AI-Generated', basic: 'Basis-Icon mit kurzem Textzusatz' },
    },
    missing: {
      title: 'Es fehlt noch: {list}',
      stamm: 'Ausmaß',
      tool: 'Tool',
      date: 'Monat der letzten Nutzung',
      host: 'Hosting',
      review: 'Review',
      acc: 'Accountability',
    },
    page: {
      invalid: 'Ungültiges Label',
      invalid_sub: 'Die URL enthält kein gültiges AI-DTL-Label. Bitte verwenden Sie den Editor.',
      code: 'Code',
      tools: 'Werkzeuge',
      not_says_title: 'Was dieses Label nicht sagt',
      not_says: 'Das Label ist eine Selbstauskunft der Erstellenden. Es sagt nichts darüber, ob der Inhalt richtig ist, und es ersetzt keine technische Herkunftsprüfung. Wo die KI-Verordnung eine Kennzeichnung verlangt, ersetzt es auch nicht das EU-Kennzeichen.',
      eu_title: 'Verhältnis zum EU-Kennzeichen',
      eu: 'Das EU-Kennzeichen steht direkt am Inhalt und sagt: Hier war KI beteiligt. Das AI-DTL kann die zweite Ebene dahinter sein und sagt, wie: was die KI gemacht hat, wo sie lief, wer geprüft hat und wer einsteht.',
      legacy04: 'Dieses Label folgt der älteren Version 0.4. Einige Begriffe sind seitdem genauer gefasst, siehe Changelog.',
      create_own: 'Eigenes Label erstellen',
      overview_title: 'Stufen und Angaben',
      overview_sub: 'So sind die Buchstaben im Code definiert.',
      cases_title: 'Grenzfälle beim Ausmaß',
      host_rule: 'Ein Unternehmen ist nie „Institutionell“. Läuft die KI auf Servern der eigenen Organisation – auch eines Unternehmens –, gilt „Lokal“.',
      cases: [
        ['Rechtschreibung und Grammatik korrigieren, einzelne Sätze glätten', 'A', 'Form geändert, Aussage unverändert'],
        ['Eigenen Text übersetzen, eigene Aufnahme transkribieren', 'A', 'Form geändert, Aussage unverändert'],
        ['Bildqualität verbessern (Belichtung, Rauschen, Schärfe)', 'A', 'Dargestelltes unverändert'],
        ['Ideen, Gliederung, Recherche, Feedback, Erklärungen', 'S', 'kein KI-Inhalt im Werk'],
        ['Fehlersuche: KI zeigt den Fehler, Sie beheben ihn selbst', 'S', 'kein KI-Inhalt im Werk'],
        ['Eigene Absätze von KI umformulieren lassen', 'M', 'vorhandenes Werk verändert'],
        ['Von der KI geänderten Code übernehmen (Fix, Refactoring)', 'M', 'vorhandenes Werk verändert'],
        ['Foto: Objekt entfernt, Hintergrund ersetzt; Stimme oder Gesicht verändert', 'M', 'vorhandenes Werk verändert'],
        ['Neuer KI-Code übernommen (Funktion, Skript, Test)', 'G', 'neu erzeugt'],
        ['Zusammenfassung, Abstract, Text aus Stichpunkten', 'G', 'neu erzeugt; Stichpunkte und Prompt sind kein vorhandenes Werk'],
        ['KI-Bild, KI-Stimme, KI-Video, Avatar', 'G', 'neu erzeugt'],
        ['KI erzeugt, danach von Ihnen überarbeitet', 'G', 'Herkunft entscheidet; die Überarbeitung zeigt R:H'],
        ['Ein KI-Bild in einem sonst eigenen Werk', 'G', 'eigenes Label am Bild, ein Label für den Rest'],
      ],
    },
    badge: {
      N: 'keine KI', A: 'assistiv', S: 'supportiv', M: 'modifiziert', G: 'generativ',
      'H:L': 'lokal', 'H:I': 'institutionell', 'H:C': 'mit Vertrag', 'H:C!': 'ohne Vertrag',
      'R:H': 'Mensch', 'R:HM': 'Mensch + Maschine', 'R:M': 'Maschine', 'R:N': 'keine Prüfung',
      'Acc:I': 'Person', 'Acc:O': 'Organisation', 'Acc:N': 'niemand',
    },
  };

  const en = {
    ui: {
      title: 'AI-DTL Generator',
      subtitle: 'Labelling AI use in five steps',
      header_version: 'v 0.5 (preview)',
      footer_draft: 'AI-DTL Working Draft 0.5 (preview)',
      skip: 'Skip to the editor',
      step: 'Step',
      doi: 'DOI to follow (Zenodo)',
      downloaded: 'Downloaded',
      multi: 'Multiple answers possible',
      single: 'One answer',
      restart: 'Start over',
      examples: 'View examples',
      more_levels: 'More about the levels',
      yes: 'Yes', no: 'No', dont_know: 'Don’t know',
      result_title: 'Your AI-DTL',
      result_intro: 'Your label consists of a sentence for readers and a code.',
      result_placeholder: 'Your label appears here once all steps are complete.',
      copied: 'Copied',
      remove_tool: 'Remove tool',
      tool_name: 'Tool',
      month: 'Month', year: 'Year',
      when_title: 'When does the editor show hints?',
      btn_text: 'Text', btn_html: 'HTML snippet', btn_md: 'Markdown', btn_latex: 'LaTeX',
      btn_link: 'Link', btn_speech: 'Spoken text', btn_svg: 'Badge ↓ SVG', btn_png: 'Badge ↓ PNG',
      study_banner: 'Study mode – your input is not stored',
      study_case: 'Case',
      study_copy: 'Copy result for the questionnaire',
      footer_test: 'Version 0.5 is currently being tested with users – feedback welcome',
      legacy_loaded: 'This label was created with version 0.4. Please check it against the 0.5 rules.',
      part_label: 'Only a single image, video or audio clip was generated or modified with AI? Recommended: a separate label directly on that element and one label for the rest of the work.',
    },
    months: SPEC_04.i18n.en.months,
    steps: {
      stamm:  { title: 'Extent – What did the AI do?', sub: 'The label shows the strongest level.' },
      tools:  { title: 'Tool – Which AI tools did you use?', sub: 'Service or model and month of last use.' },
      host:   { title: 'Hosting (H) – Where did the AI run?', sub: 'What matters is whether your input left your organisation.' },
      review: { title: 'Review (R) – Was the AI output reviewed?', sub: '' },
      acc:    { title: 'Accountability (Acc) – Who is accountable for the work?', sub: 'Machines can check, but cannot be accountable.' },
    },
    opt: {
      N: { lbl: 'No AI', dsc: 'The work was created without AI.' },
      A: { lbl: 'Assistive', dsc: 'AI assisted; content and message are yours.' },
      S: { lbl: 'Supportive', dsc: 'AI supported your work; the work contains no AI content.' },
      M: { lbl: 'Modified', dsc: 'AI changed your existing work.' },
      G: enableM
        ? { lbl: 'Generative', dsc: 'AI generated content that appears in the work.' }
        : { lbl: 'Generative', dsc: 'AI generated content that appears in the work, or changed your existing work.' },
      'H:L':  { lbl: 'Local', dsc: 'On your device or on servers of your own organisation – your input does not leave your organisation.' },
      'H:I':  { lbl: 'Institutional', dsc: 'At a trustworthy public institution outside your organisation, e.g. a scientific computing centre.' },
      'H:C':  { lbl: 'Commercial with contract', dsc: 'A company that, by contract, may not use your input for its own purposes.' },
      'H:C!': { lbl: 'Commercial without contract', dsc: 'A company without such a contract, e.g. a private or free account.' },
      'R:H':  { lbl: 'Human', dsc: 'A person reviewed the content.' },
      'R:HM': { lbl: 'Human + Machine', dsc: 'A person and software reviewed it.' },
      'R:M':  { lbl: 'Machine', dsc: 'Only software reviewed it.' },
      'R:N':  { lbl: 'None', dsc: 'The AI output was not reviewed.' },
      'Acc:I': { lbl: 'Individual', dsc: 'A named person is accountable.' },
      'Acc:O': { lbl: 'Organisational', dsc: 'An organisation is accountable.' },
      'Acc:N': { lbl: 'None', dsc: 'No one is accountable.' },
    },
    cumul: {
      stamm: 'In the label: {X} – if several apply, the strongest counts.',
      host: 'In the label: {X} – if several apply, the least protected location counts.',
    },
    helper: {
      title: 'Not sure? A few questions',
      q1: 'Does the finished work contain anything the AI generated or changed – even just a correction?',
      q1b: 'Did AI help you with ideas, structure, research or debugging?',
      q2: 'Did the AI only correct errors or smooth single sentences, translate or transcribe your own material, or improve image quality?',
      q2b: 'Did AI also help with ideas, structure, research or debugging?',
      q3: 'Has your own work been preserved and changed by the AI beyond single sentences (e.g. rephrased paragraphs, changed code, an object removed from a photo)? → M. Or did the AI produce something new, even from your material (e.g. summary, text from bullet points, new function, image, synthetic voice)? → G.',
      q3_both: 'Both',
      both_note: 'If both occur (modified and newly generated), G applies.',
      result: 'Suggestion: {X}',
      apply: 'Apply',
      again: 'Start again',
    },
    host_helper: {
      title: 'Not sure?',
      left: 'Did your input leave your organisation?',
      to: 'To whom?',
      to_public: 'Public institution',
      to_company: 'Company',
      contract: 'Is there a contract that rules out the use of your input?',
    },
    purpose: {
      label: 'What was AI used for? (optional)',
      ph: 'e.g. translating the summary, image on slide 12',
      help: 'Appears only in the sentence, not in the code.',
    },
    no_ai_hint: 'Without AI, the steps Tool, Hosting and Review are skipped.',
    tools: {
      ph: 'e.g. Ollama/Llama 4',
      date: 'Month of last use',
      add: '+ add tool',
      generic: 'Tip: add the model or version after the slash, e.g. “ChatGPT/GPT-5”.',
      host_suggest: 'Suggested for the next step: {host}, because you chose “{service}”. Please check.',
      bad_chars: 'The characters ; ( ) , | cannot be used in tool names.',
    },
    host_hint: 'A licence held by your organisation does not mean the service runs on its servers. It usually runs at the provider (Commercial with contract).',
    review_hint_as: 'For Assistive or Supportive: did you consciously accept or reject the AI’s suggestions? Then choose “Human”.',
    resp: {
      label: 'Who is accountable? (optional)',
      ph: 'e.g. Maria Muster or Musterverlag editorial team',
      help: 'Name or organisation. An ORCID or ROR ID will be linked. Appears only in the sentence.',
    },
    sentence: {
      stamm: {
        N: 'Created without AI.',
        A: 'Content by humans; AI assisted.',
        S: 'Content by humans; AI supported the work.',
        M: 'Contains content modified with AI.',
        G: 'Contains content generated with AI.',
      },
      purpose: 'AI used for: {p}.',
      reviewAS: {
        'R:H': 'AI suggestions reviewed by a human.',
        'R:HM': 'AI suggestions reviewed by a human and automatically.',
        'R:M': 'AI suggestions checked automatically only.',
        'R:N': 'AI suggestions used without review.',
      },
      reviewMG: {
        'R:H': 'AI output reviewed for substance by a human.',
        'R:HM': 'AI output reviewed for substance by a human and also checked automatically.',
        'R:M': 'AI output checked automatically only, not by a human.',
        'R:N': 'AI output not reviewed.',
      },
      resp: 'Accountable: {rp}.',
      acc: {
        'Acc:I': 'A person takes responsibility.',
        'Acc:O': 'An organisation takes responsibility.',
        'Acc:N': 'No one takes responsibility.',
      },
    },
    speech: {
      prefix: 'Note:',
      stamm: {
        N: 'This content was created without AI.',
        A: 'This content is by humans; AI assisted.',
        S: 'This content is by humans; AI supported the work.',
        M: 'This content was modified with AI.',
        G: 'This content was generated with AI.',
      },
      review: {
        'R:H': 'A person reviewed it.',
        'R:HM': 'A person and software reviewed it.',
        'R:M': 'It was checked automatically only.',
        'R:N': 'It was not reviewed.',
      },
    },
    warn: {
      hcx: 'You used a service without a contract. Did you enter personal or confidential data? That is usually not permitted.',
      mg_rn: 'AI content was adopted without review. Check facts and sources before publishing.',
      mg_rm: 'Automated checks alone do not replace human review.',
      accn: 'No one takes responsibility. Would “Organisational” fit better?',
    },
    art50: {
      title: 'Does the content also need the EU label?',
      question: 'Will the content be published and is it (a) a realistic image, audio or video showing or altering real people, places or events, or (b) a text meant to inform the public on matters of public interest that no human reviewed for substance or for which no person or body publicly takes editorial responsibility?',
      yes: 'Then Art. 50 of the AI Act requires a visible notice directly on the content, at the latest at first contact – at the start of a video, spoken for audio. The EU labels exist for this. The AI-DTL can sit behind it as a second layer. Likely fitting: {icon}. This is not legal advice.',
      link: 'To the EU labels',
      no: 'Then the AI-DTL is a voluntary statement.',
      unknown: 'If in doubt, label additionally. Ask the office responsible.',
      icons: { partial: 'Partially AI-Modified', full: 'Fully AI-Generated', basic: 'basic icon with a short text addition' },
    },
    missing: {
      title: 'Still missing: {list}',
      stamm: 'Extent',
      tool: 'Tool',
      date: 'Month of last use',
      host: 'Hosting',
      review: 'Review',
      acc: 'Accountability',
    },
    page: {
      invalid: 'Invalid label',
      invalid_sub: 'This URL does not contain a valid AI-DTL label. Please use the editor.',
      code: 'Code',
      tools: 'Tools',
      not_says_title: 'What this label does not say',
      not_says: 'The label is a self-declaration by its creators. It says nothing about whether the content is correct, and it does not replace technical provenance checks. Where the AI Act requires labelling, it does not replace the EU label either.',
      eu_title: 'Relation to the EU label',
      eu: 'The EU label sits directly on the content and says: AI was involved here. The AI-DTL can be the second layer behind it and says how: what the AI did, where it ran, who reviewed it and who is accountable.',
      legacy04: 'This label follows the older version 0.4. Some terms have since been defined more precisely, see the changelog.',
      create_own: 'Create your own label',
      overview_title: 'Levels and statements',
      overview_sub: 'How the letters in the code are defined.',
      cases_title: 'Borderline cases for the extent',
      host_rule: 'A company is never “Institutional”. If the AI runs on servers of your own organisation – a company’s included –, “Local” applies.',
      cases: [
        ['Correcting spelling and grammar, smoothing single sentences', 'A', 'form changed, message unchanged'],
        ['Translating your own text, transcribing your own recording', 'A', 'form changed, message unchanged'],
        ['Improving image quality (exposure, noise, sharpness)', 'A', 'what is shown is unchanged'],
        ['Ideas, structure, research, feedback, explanations', 'S', 'no AI content in the work'],
        ['Debugging: the AI points out the error, you fix it yourself', 'S', 'no AI content in the work'],
        ['Having the AI rephrase your own paragraphs', 'M', 'existing work changed'],
        ['Adopting code changed by the AI (fix, refactoring)', 'M', 'existing work changed'],
        ['Photo: object removed, background replaced; voice or face altered', 'M', 'existing work changed'],
        ['New AI code adopted (function, script, test)', 'G', 'newly generated'],
        ['Summary, abstract, text from bullet points', 'G', 'newly generated; bullet points and prompts are not existing work'],
        ['AI image, AI voice, AI video, avatar', 'G', 'newly generated'],
        ['Generated by AI, then revised by you', 'G', 'origin decides; the revision shows as R:H'],
        ['One AI image in an otherwise own work', 'G', 'separate label on the image, one label for the rest'],
      ],
    },
    badge: {
      N: 'no AI', A: 'assistive', S: 'supportive', M: 'modified', G: 'generative',
      'H:L': 'local', 'H:I': 'institutional', 'H:C': 'with contract', 'H:C!': 'no contract',
      'R:H': 'human', 'R:HM': 'human + machine', 'R:M': 'machine', 'R:N': 'not reviewed',
      'Acc:I': 'individual', 'Acc:O': 'organisation', 'Acc:N': 'no one',
    },
  };

  if (!enableM) {
    [de, en].forEach(t => {
      delete t.opt.M; delete t.sentence.stamm.M; delete t.speech.stamm.M; delete t.badge.M;
      delete t.helper.q3; delete t.helper.q3_both; delete t.helper.both_note;
      // borderline cases for M count as G without level M
      t.page.cases = t.page.cases.map(([s, c, r]) => [s, c === 'M' ? 'G' : c, r]);
    });
  }

  return {
    version: '0.5',
    enableM,
    codes: {
      stamm:  stammRank,
      host:   { 'H:C!': 0, 'H:C': 1, 'H:I': 2, 'H:L': 3 },
      review: { 'R:H': 0, 'R:HM': 1, 'R:M': 2, 'R:N': 3 },
      acc:    { 'Acc:I': 0, 'Acc:O': 1, 'Acc:N': 2 },
    },
    order: {
      stamm:  stammOrder,
      host:   ['H:L', 'H:I', 'H:C', 'H:C!'],
      review: ['R:H', 'R:HM', 'R:M', 'R:N'],
      acc:    ['Acc:I', 'Acc:O', 'Acc:N'],
    },
    rules: {
      noAiAcc: ['Acc:I', 'Acc:O'],
      noAiAccLegacy: ['Acc:I', 'Acc:O'],
      toolRequired: true,
      dateRequired: true,
      toolNameMax: 80,
      freeTextMax: 120,
    },
    warnings: [
      { id: 'hcx',   trigger: 'H:C!',        when: s => s.host === 'H:C!' },
      { id: 'mg_rn', trigger: enableM ? 'M/G + R:N' : 'G + R:N', when: s => mg(s) && s.review === 'R:N' },
      { id: 'mg_rm', trigger: enableM ? 'M/G + R:M' : 'G + R:M', when: s => mg(s) && s.review === 'R:M' },
      { id: 'accn',  trigger: 'Acc:N',       when: s => s.acc === 'Acc:N' },
    ],
    euLabelsUrl: 'https://digital-strategy.ec.europa.eu/en/policies/eu-icons-labelling-ai-generated-content',
    i18n: { de, en },
  };
}

const SPEC = {
  '0.4': deepFreeze(SPEC_04),
  '0.5': deepFreeze(buildSpec05(ENABLE_M)),
};

if (typeof module !== 'undefined') {
  module.exports = { SITE_BASE, ENABLE_M, SPEC, buildSpec05: m => deepFreeze(buildSpec05(m)) };
}
