// ── AI-DTL specification registry
// One place for codes, rules and texts. Editor, explanation page and tests read from here.
// SPEC['0.4'] is frozen (texts as published in June 2026). SPEC['0.5'] follows the
// revision plan, Annex A; ENABLE_M switches the provisional level M (decision E3).

// Canonical base URL of this copy of the site; shared links always point here.
// Release candidate: links point to rc/label/?v=0.5… until 0.5 is released (Phase 7).
const SITE_BASE = 'https://joshuadohmen-sketch.github.io/AIDL/rc/';

// Provisional (E3): level M "existing work modified". false → all "[ohne M]" texts apply.
const ENABLE_M = true;

function deepFreeze(o) {
  Object.values(o).forEach(v => { if (v && typeof v === 'object' && !Object.isFrozen(v)) deepFreeze(v); });
  return Object.freeze(o);
}

// ── Version 0.4 (frozen) ─────────────────────────────────────────────────────
const SPEC_04 = {
  version: '0.4',
  // rank: stamm – higher is stronger; host – lower is less protected
  codes: {
    stamm:  { N: 0, A: 1, S: 2, G: 3 },
    host:   { 'H:C!': 0, 'H:C': 1, 'H:I': 2, 'H:L': 3 },
    review: { 'R:H': 0, 'R:M': 1, 'R:HM': 2, 'R:N': 3 },
    acc:    { 'Acc:I': 0, 'Acc:O': 1, 'Acc:N': 2 },
  },
  order: {
    stamm:  ['N', 'A', 'S', 'G'],
    host:   ['H:L', 'H:I', 'H:C', 'H:C!'],
    review: ['R:H', 'R:M', 'R:HM', 'R:N'],
    acc:    ['Acc:I', 'Acc:O', 'Acc:N'],
  },
  rules: {
    noAiAcc: ['Acc:I', 'Acc:O'],          // what the editor can produce
    noAiAccLegacy: ['Acc:I', 'Acc:O', 'Acc:N'], // what old links may contain
    toolRequired: false,
    dateRequired: false,
    toolDisplayMax: 200,
  },
  warnings: [
    { id: 'hcx',    trigger: 'H:C!',      when: s => s.host === 'H:C!' },
    { id: 'g_rn',   trigger: 'G + R:N',   when: s => s.stamm === 'G' && s.review === 'R:N' },
    { id: 'g_accn', trigger: 'G + Acc:N', when: s => s.stamm === 'G' && s.acc === 'Acc:N' },
  ],
  i18n: {
    de: {
      ui: {
        hero_title: 'AI Disclosure & Transparency Label Generator',
        hero_desc: 'Generieren Sie ein valides AI-DTL 0.4 für Ihr Artefakt.',
        step: 'Schritt 1', step2: 'Schritt 2', step3: 'Schritt 3', step4: 'Schritt 4', step5: 'Schritt 5',
        s1_title: 'Ausmaß der KI-Nutzung',         s1_sub: 'Wie stark war KI an der Entstehung des Artefakts beteiligt?',
        s1_hint: 'Mehrfachauswahl möglich – bei mehreren Stufen zählt die höchste tatsächliche Wirkung.',
        s2_title: 'Hosting-Kontext',                s2_sub: 'Wo lief das KI-System? Relevant für Datenschutz und DFG-Konformität.',
        s2_hint: 'Mehrfachauswahl möglich – bei mehreren Hosts zählt der am wenigsten geschützte.',
        s3_title: 'Prüfung der KI-Ausgaben',        s3_sub: 'Wurden die KI-Ausgaben geprüft, bevor sie übernommen wurden?',
        s4_title: 'Accountability – Verantwortung', s4_sub: 'Wer steht für das Artefakt ein?',
        s5_title: 'Tool-Angabe',                    s5_sub: 'Welches KI-System wurde verwendet? Name, Version und Monat der Nutzung.',
        tool_ph: 'z.B. Claude Opus 4.6', tool_aria: 'KI-Tool Name',
        btn_add_tool: '+ weiteres Tool', remove_tool_aria: 'Tool entfernen',
        warn_when_title: 'Wann warnt der Generator?',
        result_label: 'Ihr AI-DTL-Label',
        result_ph: 'Bitte alle Felder ausfüllen …',
        btn_text: 'Text kopieren', btn_meta: 'HTML <meta>', btn_md: 'Markdown',
        btn_latex: 'LaTeX', btn_link: 'Link kopieren',
        btn_badge: 'Badge ↓ SVG', btn_png: 'Badge ↓ PNG',
        no_ai_hint: 'Bei N entfallen Host, Review und Tool. Bitte Accountability auswählen.',
        alert_incomplete: 'Bitte zuerst alle Felder ausfüllen.',
        month_ph: 'Monat', year_ph: 'Jahr',
      },
      months: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
      opt: {
        N:      { lbl: 'No AI',            dsc: 'Keine KI-Beteiligung am Artefakt' },
        A:      { lbl: 'Assistive',        dsc: 'Sprachpolitur, Rechtschreibkorrektur, Übersetzung' },
        S:      { lbl: 'Supportive',       dsc: 'Brainstorming, Gliederung, Recherche-Hilfe' },
        G:      { lbl: 'Generative',       dsc: 'Substantielle Text-, Code- oder Datengenerierung' },
        'H:L':  { lbl: 'Local',            dsc: 'Lokal ausgeführt, keine Datenübertragung (z.B. Ollama)' },
        'H:I':  { lbl: 'Institutional',    dsc: 'Hochschul- oder Behördeninstanz mit interner AVV' },
        'H:C':  { lbl: 'Cloud w/ DPA',     dsc: 'Kommerzieller Cloud-Dienst mit Auftragsverarbeitungsvertrag' },
        'H:C!': { lbl: 'Cloud w/o DPA',    dsc: 'Ohne AVV – in vielen Kontexten unzulässig' },
        'R:H':  { lbl: 'Human reviewed',   dsc: 'Menschliche Prüfung der KI-Ausgaben' },
        'R:M':  { lbl: 'Machine reviewed', dsc: 'Automatisierte Prüfung (Linter, Faktenchecker)' },
        'R:HM': { lbl: 'Both',             dsc: 'Mensch und Maschine haben geprüft' },
        'R:N':  { lbl: 'None',             dsc: 'Keine Prüfung – Ausgabe unverändert übernommen' },
        'Acc:I': { lbl: 'Individual',      dsc: 'Benennbare Einzelperson (z.B. Autor:in mit ORCID)' },
        'Acc:O': { lbl: 'Organizational',  dsc: 'Organisation übernimmt Verantwortung' },
        'Acc:N': { lbl: 'None claimed',    dsc: 'Rein agentischer Raum – kein Mensch steht ein' },
      },
      exp: {
        N: 'Keine KI-Beteiligung', A: 'Assistive Nutzung', S: 'Supportive Nutzung', G: 'Generative Nutzung',
        'H:L': 'lokal gehostet', 'H:I': 'institutionell gehostet', 'H:C': 'Cloud mit AVV', 'H:C!': '⚠ Cloud ohne AVV',
        'R:H': 'menschlich geprüft', 'R:M': 'maschinell geprüft', 'R:HM': 'Mensch & Maschine', 'R:N': '⚠ nicht geprüft',
        'Acc:I': 'Einzelperson verantwortlich', 'Acc:O': 'Organisation verantwortlich', 'Acc:N': '⚠ keine Accountability',
      },
      warn: {
        hcx:    'Cloud-Nutzung ohne Auftragsverarbeitungsvertrag (AVV): Wenn Sie personenbezogene oder vertrauliche Daten eingegeben haben, ist das in der Regel nicht zulässig.',
        g_rn:   'Generative KI-Ausgaben wurden ungeprüft übernommen. Prüfen Sie Fakten und Quellen vor der Veröffentlichung.',
        g_accn: 'Für generative KI-Inhalte ist keine Verantwortung angegeben. Passt „Organizational“?',
      },
      page: {
        page_sub: 'Dieses Artefakt trägt folgendes AI-DTL-Label:',
        create_own: 'Eigenes Label erstellen',
        create_sub: 'Verwenden Sie den AI-DTL Generator, um ein Label für Ihr Artefakt zu erzeugen.',
        invalid: 'Ungültiges Label',
        invalid_sub: 'Die URL enthält kein gültiges AI-DTL-Label. Bitte verwenden Sie den Generator.',
        tool_used: 'Verwendetes KI-System',
        legacy_n_accn: 'Diese Kombination ist seit Version 0.4 nicht mehr vorgesehen.',
      },
      dims: {
        N:      { title: 'Keine KI-Beteiligung',         desc: 'Dieses Artefakt wurde vollständig ohne KI-Unterstützung erstellt.' },
        A:      { title: 'Assistive KI-Nutzung',         desc: 'KI wurde ausschließlich für Hilfsfunktionen wie Sprachpolitur, Rechtschreibkorrektur oder Übersetzung eingesetzt.' },
        S:      { title: 'Supportive KI-Nutzung',        desc: 'KI unterstützte beim Brainstorming, bei der Gliederung oder bei der Recherche. Die inhaltliche Gestaltung lag beim Menschen.' },
        G:      { title: 'Generative KI-Nutzung',        desc: 'KI hat substantielle Teile dieses Artefakts erzeugt – Text, Code oder Daten wurden maßgeblich von KI generiert.' },
        'H:L':  { title: 'Lokales Hosting',              desc: 'Das KI-System lief lokal auf dem eigenen Rechner. Es wurden keine Daten an externe Server übertragen.' },
        'H:I':  { title: 'Institutionelles Hosting',     desc: 'Das KI-System wurde auf einer Hochschul- oder Behördeninstanz betrieben, mit interner Auftragsverarbeitung (AVV).' },
        'H:C':  { title: 'Cloud-Hosting mit AVV',        desc: 'Ein kommerzieller Cloud-Dienst wurde genutzt, für den ein Auftragsverarbeitungsvertrag (AVV/DPA) besteht.' },
        'H:C!': { title: 'Cloud-Hosting ohne AVV',       desc: 'Ein kommerzieller Cloud-Dienst wurde ohne Auftragsverarbeitungsvertrag genutzt. Dies ist in vielen institutionellen Kontexten unzulässig.' },
        'R:H':  { title: 'Menschlich geprüft',           desc: 'Die KI-Ausgaben wurden von einem Menschen inhaltlich geprüft, bevor sie übernommen wurden.' },
        'R:M':  { title: 'Maschinell geprüft',           desc: 'Die KI-Ausgaben wurden automatisiert geprüft (z.B. durch Linter, Faktenchecker oder Validierungstools).' },
        'R:HM': { title: 'Mensch & Maschine geprüft',    desc: 'Sowohl ein Mensch als auch automatisierte Systeme haben die KI-Ausgaben geprüft.' },
        'R:N':  { title: 'Keine Prüfung',                desc: 'Die KI-Ausgaben wurden ungeprüft und unverändert übernommen. Dies birgt ein erhöhtes Risiko für Fehler und Halluzinationen.' },
        'Acc:I': { title: 'Individuelle Verantwortung',  desc: 'Eine benennbare Einzelperson (z.B. Autor:in mit ORCID) steht für dieses Artefakt ein.' },
        'Acc:O': { title: 'Organisatorische Verantwortung', desc: 'Eine Organisation übernimmt die Verantwortung für dieses Artefakt.' },
        'Acc:N': { title: 'Keine Verantwortung deklariert', desc: 'Niemand hat die Verantwortung für dieses Artefakt übernommen. Es handelt sich um einen rein agentischen Kontext.' },
      },
    },
    en: {
      ui: {
        hero_title: 'AI Disclosure & Transparency Label Generator',
        hero_desc: 'Generate a valid AI-DTL 0.4 for your artefact.',
        step: 'Step 1', step2: 'Step 2', step3: 'Step 3', step4: 'Step 4', step5: 'Step 5',
        s1_title: 'Extent of AI Use',    s1_sub: 'How deeply was AI involved in creating this artefact?',
        s1_hint: 'Multiple selection possible – when multiple levels apply, the highest effective level is coded.',
        s2_title: 'Hosting Context',     s2_sub: 'Where did the AI run? Relevant for data protection and DFG compliance.',
        s2_hint: 'Multiple selection possible – when multiple hosts apply, the least protected is coded.',
        s3_title: 'Review of AI Output', s3_sub: 'Was the AI output reviewed before being adopted?',
        s4_title: 'Accountability',      s4_sub: 'Who is accountable for this artefact?',
        s5_title: 'Tool Declaration',    s5_sub: 'Which AI system was used? Provide name, version, and month of use.',
        tool_ph: 'e.g. Claude Opus 4.6', tool_aria: 'AI tool name',
        btn_add_tool: '+ add tool', remove_tool_aria: 'Remove tool',
        warn_when_title: 'When does the generator warn?',
        result_label: 'Your AI-DTL Label',
        result_ph: 'Please complete all fields …',
        btn_text: 'Copy text', btn_meta: 'HTML <meta>', btn_md: 'Markdown',
        btn_latex: 'LaTeX', btn_link: 'Copy link',
        btn_badge: 'Badge ↓ SVG', btn_png: 'Badge ↓ PNG',
        no_ai_hint: 'For N, Host, Review and Tool are omitted. Please select Accountability.',
        alert_incomplete: 'Please complete all fields first.',
        month_ph: 'Month', year_ph: 'Year',
      },
      months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      opt: {
        N:      { lbl: 'No AI',            dsc: 'No AI involvement in the artefact' },
        A:      { lbl: 'Assistive',        dsc: 'Language polishing, spell-check, translation' },
        S:      { lbl: 'Supportive',       dsc: 'Brainstorming, structuring, research support' },
        G:      { lbl: 'Generative',       dsc: 'Substantial text, code, or data generation by AI' },
        'H:L':  { lbl: 'Local',            dsc: 'Locally executed, no data transfer (e.g. Ollama)' },
        'H:I':  { lbl: 'Institutional',    dsc: 'University or authority instance with internal DPA' },
        'H:C':  { lbl: 'Cloud w/ DPA',     dsc: 'Commercial cloud service with data processing agreement' },
        'H:C!': { lbl: 'Cloud w/o DPA',    dsc: 'No DPA – unlawful in many contexts' },
        'R:H':  { lbl: 'Human reviewed',   dsc: 'Human review of AI output' },
        'R:M':  { lbl: 'Machine reviewed', dsc: 'Automated review (linter, fact-checker)' },
        'R:HM': { lbl: 'Both',             dsc: 'Human and machine reviewed' },
        'R:N':  { lbl: 'None',             dsc: 'No review – AI output adopted unchanged' },
        'Acc:I': { lbl: 'Individual',      dsc: 'Named individual (e.g. author with ORCID)' },
        'Acc:O': { lbl: 'Organizational',  dsc: 'Organization takes responsibility' },
        'Acc:N': { lbl: 'None claimed',    dsc: 'Purely agentic context – no human stands behind this' },
      },
      exp: {
        N: 'No AI involvement', A: 'Assistive use', S: 'Supportive use', G: 'Generative use',
        'H:L': 'locally hosted', 'H:I': 'institutionally hosted', 'H:C': 'cloud with DPA', 'H:C!': '⚠ cloud without DPA',
        'R:H': 'human reviewed', 'R:M': 'machine reviewed', 'R:HM': 'human & machine', 'R:N': '⚠ not reviewed',
        'Acc:I': 'individual accountable', 'Acc:O': 'organization accountable', 'Acc:N': '⚠ no accountability',
      },
      warn: {
        hcx:    'Cloud use without a data processing agreement (DPA): if you entered personal or confidential data, this is usually not permitted.',
        g_rn:   'Generative AI output was adopted without review. Check facts and sources before publishing.',
        g_accn: 'No accountability is declared for generative AI content. Would “Organizational” fit?',
      },
      page: {
        page_sub: 'This artefact carries the following AI-DTL label:',
        create_own: 'Create your own label',
        create_sub: 'Use the AI-DTL Generator to create a label for your artefact.',
        invalid: 'Invalid label',
        invalid_sub: 'This URL does not contain a valid AI-DTL label. Please use the generator.',
        tool_used: 'AI system used',
        legacy_n_accn: 'This combination is no longer intended since version 0.4.',
      },
      dims: {
        N:      { title: 'No AI involvement',            desc: 'This artefact was created entirely without AI assistance.' },
        A:      { title: 'Assistive AI use',             desc: 'AI was used only for auxiliary functions such as language polishing, spell-checking, or translation.' },
        S:      { title: 'Supportive AI use',            desc: 'AI assisted with brainstorming, structuring, or research. The substantive content was created by a human.' },
        G:      { title: 'Generative AI use',            desc: 'AI generated substantial parts of this artefact – text, code, or data were significantly produced by AI.' },
        'H:L':  { title: 'Local hosting',                desc: 'The AI system ran locally on the user\'s own machine. No data was transmitted to external servers.' },
        'H:I':  { title: 'Institutional hosting',        desc: 'The AI system was operated on a university or authority instance with an internal data processing agreement.' },
        'H:C':  { title: 'Cloud hosting with DPA',       desc: 'A commercial cloud service was used under a data processing agreement (DPA).' },
        'H:C!': { title: 'Cloud hosting without DPA',    desc: 'A commercial cloud service was used without a data processing agreement. This may be unlawful in many institutional contexts.' },
        'R:H':  { title: 'Human reviewed',               desc: 'The AI outputs were reviewed by a human before being adopted.' },
        'R:M':  { title: 'Machine reviewed',             desc: 'The AI outputs were checked by automated tools (e.g. linters, fact-checkers, or validation tools).' },
        'R:HM': { title: 'Human & machine reviewed',     desc: 'Both a human and automated systems reviewed the AI outputs.' },
        'R:N':  { title: 'No review',                    desc: 'The AI outputs were adopted without any review. This carries an elevated risk of errors and hallucinations.' },
        'Acc:I': { title: 'Individual accountability',   desc: 'A named individual (e.g. author with ORCID) is accountable for this artefact.' },
        'Acc:O': { title: 'Organizational accountability', desc: 'An organization takes responsibility for this artefact.' },
        'Acc:N': { title: 'No accountability claimed',   desc: 'Nobody has claimed responsibility for this artefact. This is a purely agentic context.' },
      },
    },
  },
};

// ── Version 0.5 (texts: revision plan, Annex A and B) ───────────────────────
function buildSpec05(enableM) {
  const stammOrder = enableM ? ['N', 'A', 'S', 'M', 'G'] : ['N', 'A', 'S', 'G'];
  const stammRank = {};
  stammOrder.forEach((c, i) => { stammRank[c] = i; });

  const mg = s => s.stamm === 'M' || s.stamm === 'G';

  const de = {
    ui: {
      title: 'AI-DTL – KI-Nutzung offenlegen',
      subtitle: 'In fünf Schritten zu einem Label aus Klartextsatz und Code.',
      header_version: 'v 0.5 (Vorschau)',
      skip: 'Zum Editor springen',
      step: 'Schritt',
      doi: 'DOI folgt (Zenodo)',
      downloaded: 'Heruntergeladen',
      multi: 'Mehrfachauswahl möglich',
      single: 'Eine Auswahl',
      restart: 'Neu beginnen',
      example: 'Beispiel laden',
      example_none: '– Beispiel wählen –',
      yes: 'Ja', no: 'Nein', dont_know: 'Weiß nicht',
      result_title: 'Ihr AI-DTL',
      copied: 'Kopiert',
      remove_tool: 'Werkzeug entfernen',
      tool_name: 'Werkzeug',
      month: 'Monat', year: 'Jahr',
      when_title: 'Wann gibt der Editor Hinweise?',
      btn_text: 'Text', btn_html: 'HTML-Baustein', btn_md: 'Markdown', btn_latex: 'LaTeX',
      btn_link: 'Link', btn_speech: 'Sprechtext', btn_svg: 'Badge ↓ SVG', btn_png: 'Badge ↓ PNG',
      study_banner: 'Studienmodus – Ihre Eingaben werden nicht gespeichert',
      study_case: 'Fall',
      study_copy: 'Ergebnis für den Fragebogen kopieren',
      footer_test: 'Version 0.5 wird gerade mit Nutzer:innen getestet – Feedback willkommen',
      legacy_loaded: 'Dieses Label wurde mit Version 0.4 erstellt. Bitte prüfen Sie die Angaben nach den Regeln von 0.5.',
      part_label: 'Nur ein einzelnes Bild, Video oder Tonstück ist mit KI erzeugt oder verändert? Empfehlung: ein eigenes Label direkt an diesem Element und ein Label für den Rest des Werks.',
    },
    months: SPEC_04.i18n.de.months,
    steps: {
      stamm:  { title: 'Was hat die KI gemacht?', sub: 'Wählen Sie alles, was zutrifft. Im Label zählt die stärkste Stufe.' },
      tools:  { title: 'Welche KI-Werkzeuge haben Sie genutzt?', sub: 'Name des Dienstes und, falls bekannt, das Modell. Dazu der Monat, in dem Sie das Werkzeug zuletzt für dieses Werk genutzt haben.' },
      host:   { title: 'Auf wessen Rechnern lief die KI?', sub: 'Entscheidend ist, wo Ihre Eingaben verarbeitet wurden – nicht, wer das Modell entwickelt hat.' },
      review: { title: 'Wurden die KI-Ausgaben geprüft?', sub: '' },
      acc:    { title: 'Wer steht für das Werk ein?', sub: 'Maschinen können prüfen, aber nicht einstehen.' },
    },
    opt: {
      N: { lbl: 'Keine KI', dsc: 'Ohne KI erstellt. Die Rechtschreibprüfung im Textprogramm zählt nicht.' },
      A: { lbl: 'Sprache und Form', dsc: 'KI hat nur Fehler korrigiert oder einzelne Sätze geglättet, eigene Texte übersetzt oder transkribiert oder die Bildqualität verbessert. Wortlaut und Darstellung stammen im Wesentlichen von Ihnen.' },
      S: { lbl: 'Hilfe im Arbeitsprozess', dsc: 'KI half bei Ideen, Gliederung, Recherche, Feedback oder Fehlersuche. Im fertigen Werk steht kein KI-Inhalt.' },
      M: { lbl: 'Bestehendes verändert', dsc: 'KI hat Ihr vorhandenes Werk über einzelne Sätze hinaus umgestaltet: Absätze umformuliert, Code geändert (Fix, Refactoring), ein Foto inhaltlich bearbeitet (Objekte entfernt, Hintergrund ersetzt), Stimme oder Gesicht in einer Aufnahme verändert.' },
      G: enableM
        ? { lbl: 'Neu erzeugt', dsc: 'KI hat Inhalte neu erzeugt, die im Werk stehen: Text, Zusammenfassung, Code, Daten, Bild, Ton oder Video – auch aus Ihrem Material und auch wenn Sie sie danach überarbeitet haben.' }
        : { lbl: 'KI-Inhalte im Werk', dsc: 'KI hat Inhalte neu erzeugt, die im Werk stehen: Text, Zusammenfassung, Code, Daten, Bild, Ton oder Video – auch aus Ihrem Material und auch wenn Sie sie danach überarbeitet haben – oder Vorhandenes verändert: Absätze umformuliert, Code geändert, Foto bearbeitet, Stimme verändert.' },
      'H:L':  { lbl: 'Eigenes Gerät', dsc: 'Auf Ihrem Rechner (auch Ihrem Dienstrechner) oder einem Server unter Ihrer eigenen Kontrolle, z. B. mit Ollama. Keine Übertragung an Dritte.' },
      'H:I':  { lbl: 'Wissenschaftliche Einrichtung', dsc: 'Im Rechenzentrum einer Hochschule oder öffentlichen Forschungseinrichtung, z. B. offene Modelle in der Academic Cloud (GWDG).' },
      'H:C':  { lbl: 'Anbieter mit Vertrag', dsc: 'Bei einem kommerziellen Anbieter, mit dem Ihre Einrichtung einen Vertrag hat, der ihm verbietet, Ihre Eingaben für eigene Zwecke (z. B. Training) zu verwenden, z. B. Microsoft 365 Copilot mit Hochschullizenz.' },
      'H:C!': { lbl: 'Anbieter ohne Vertrag', dsc: 'Bei einem kommerziellen Anbieter ohne solchen Vertrag, z. B. privates oder kostenloses Konto.' },
      'R:H':  { lbl: 'Von einem Menschen', dsc: 'Ein Mensch hat den Inhalt geprüft, nicht nur die Form – etwa Fakten, Quellen, Aussagen –, und zwar nach der letzten KI-Änderung.' },
      'R:HM': { lbl: 'Mensch und Software', dsc: 'Wie oben, zusätzlich automatische Prüfungen (z. B. Tests, Linter).' },
      'R:M':  { lbl: 'Nur Software', dsc: 'Nur automatische Prüfungen. Das gilt nicht als menschliche Prüfung.' },
      'R:N':  { lbl: 'Nicht geprüft', dsc: 'KI-Ausgaben wurden ungeprüft übernommen.' },
      'Acc:I': { lbl: 'Eine Person', dsc: 'Sie selbst oder eine andere benannte Person, z. B. die Autorin oder der Autor.' },
      'Acc:O': { lbl: 'Eine Organisation', dsc: 'Die Einrichtung, in deren Namen veröffentlicht wird, z. B. Hochschule, Referat, Redaktion.' },
      'Acc:N': { lbl: 'Niemand', dsc: 'Weder eine Person noch eine Organisation übernimmt Verantwortung. Im Hochschulbetrieb selten.' },
    },
    cumul: {
      stamm: 'Im Label: {X} – bei mehreren Stufen zählt die stärkste.',
      host: 'Im Label: {X} – bei mehreren zählt der am wenigsten geschützte Ort.',
    },
    helper: {
      title: 'Unsicher? Ein paar Fragen',
      q1: 'Steht im fertigen Werk etwas, das die KI erzeugt oder verändert hat – und sei es nur eine Korrektur?',
      q1b: 'Hat KI Ihnen bei Ideen, Gliederung, Recherche oder Fehlersuche geholfen?',
      q2: 'Hat die KI nur Fehler korrigiert oder einzelne Sätze geglättet, eigene Texte übersetzt oder transkribiert oder die Bildqualität verbessert?',
      q2b: 'Hat KI außerdem bei Ideen, Gliederung, Recherche oder Fehlersuche geholfen?',
      q3: 'Ist Ihr eigenes Werk erhalten geblieben und wurde von der KI über einzelne Sätze hinaus verändert (z. B. Absätze umformuliert, Code geändert, ein Objekt aus einem Foto entfernt)? → M. Oder hat die KI etwas Neues hervorgebracht, auch aus Ihrem Material (z. B. Zusammenfassung, Text aus Stichpunkten, neue Funktion, Bild, synthetische Stimme)? → G.',
      q3_both: 'Beides',
      both_note: 'Kommt beides vor (Verändertes und neu Erzeugtes), gilt G.',
      result: 'Vorschlag: {X}',
      apply: 'Übernehmen',
      again: 'Noch einmal',
    },
    purpose: {
      label: 'Wofür wurde KI eingesetzt? (optional)',
      ph: 'z. B. Übersetzung der Zusammenfassung, Bild auf Folie 12',
      help: 'Erscheint nur im Klartextsatz, nicht im Code.',
    },
    no_ai_hint: 'Ohne KI entfallen die Schritte zu Werkzeug, Rechnern und Prüfung.',
    tools: {
      ph: 'z. B. Academic Cloud/Llama 3.3 70B',
      date: 'Monat der letzten Nutzung',
      add: '+ weiteres Werkzeug',
      generic: 'Tipp: Ergänzen Sie hinter dem Schrägstrich Modell oder Version, z. B. „ChatGPT/GPT-5“.',
      host_suggest: 'Vorschlag für den nächsten Schritt: {host}, weil Sie „{service}“ gewählt haben. Bitte prüfen.',
      bad_chars: 'Die Zeichen ; ( ) , | sind im Werkzeugnamen nicht möglich.',
    },
    host_hint: 'Uni-Lizenz heißt nicht Uni-Rechner: Ein Dienst mit Hochschullizenz läuft meist beim Anbieter (Anbieter mit Vertrag).',
    review_hint_as: 'Bei „Sprache und Form“ oder „Hilfe im Arbeitsprozess“: Haben Sie die Vorschläge der KI bewusst angenommen oder verworfen? Dann „Von einem Menschen“.',
    resp: {
      label: 'Wer steht dafür ein? (optional)',
      ph: 'z. B. Dr. Maria Muster oder Referat Hochschulkommunikation',
      help: 'Name oder Einrichtung. Eine ORCID oder ROR-ID können Sie anhängen, sie wird verlinkt. Erscheint nur im Klartextsatz.',
    },
    sentence: {
      stamm: {
        N: 'Ohne KI erstellt.',
        A: 'Inhalt von Menschen; KI half nur bei Sprache oder Form.',
        S: 'Inhalt von Menschen; KI half im Arbeitsprozess.',
        M: 'Enthält mit KI veränderte Inhalte.',
        G: 'Enthält mit KI erzeugte Inhalte.',
      },
      purpose: 'KI eingesetzt für: {p}.',
      reviewAS: {
        'R:H': 'KI-Vorschläge von einem Menschen geprüft.',
        'R:HM': 'KI-Vorschläge von einem Menschen und automatisch geprüft.',
        'R:M': 'KI-Vorschläge nur automatisch geprüft.',
        'R:N': 'KI-Vorschläge ohne Prüfung genutzt.',
      },
      reviewMG: {
        'R:H': 'KI-Ausgaben von einem Menschen inhaltlich geprüft.',
        'R:HM': 'KI-Ausgaben von einem Menschen inhaltlich und zusätzlich automatisch geprüft.',
        'R:M': 'KI-Ausgaben nur automatisch geprüft, nicht von einem Menschen.',
        'R:N': 'KI-Ausgaben nicht geprüft.',
      },
      resp: 'Verantwortlich: {rp}.',
      acc: {
        'Acc:I': 'Eine Person übernimmt die Verantwortung.',
        'Acc:O': 'Eine Organisation übernimmt die Verantwortung.',
        'Acc:N': 'Niemand übernimmt die Verantwortung.',
      },
      tool: 'Werkzeug: {list}.',
      tools: 'Werkzeuge: {list}.',
    },
    speech: {
      prefix: 'Hinweis:',
      stamm: {
        N: 'Dieser Inhalt wurde ohne KI erstellt.',
        A: 'Dieser Inhalt stammt von Menschen; KI half nur bei Sprache oder Form.',
        S: 'Dieser Inhalt stammt von Menschen; KI half im Arbeitsprozess.',
        M: 'Dieser Inhalt wurde mit KI verändert.',
        G: 'Dieser Inhalt wurde mit KI erzeugt.',
      },
      review: {
        'R:H': 'Ein Mensch hat ihn geprüft.',
        'R:HM': 'Ein Mensch und eine Software haben ihn geprüft.',
        'R:M': 'Er wurde nur automatisch geprüft.',
        'R:N': 'Er wurde nicht geprüft.',
      },
    },
    warn: {
      hcx: 'Sie haben einen Dienst ohne Vertrag genutzt. Haben Sie personenbezogene oder vertrauliche Daten eingegeben? Dann ist das in der Regel nicht zulässig.',
      mg_rn: 'KI-Inhalte wurden ungeprüft übernommen. Prüfen Sie Fakten und Quellen vor der Veröffentlichung.',
      mg_rm: 'Eine nur automatische Prüfung ersetzt keine menschliche Prüfung.',
      accn: 'Niemand übernimmt Verantwortung. Passt eher „Eine Organisation“?',
    },
    art50: {
      title: 'Muss zusätzlich das EU-Kennzeichen an den Inhalt?',
      question: 'Wird der Inhalt veröffentlicht und ist er (a) ein realistisch wirkendes Bild, Ton oder Video, das echte Personen, Orte oder Ereignisse zeigt oder verändert, oder (b) ein Text, der die Öffentlichkeit über Angelegenheiten von öffentlichem Interesse informieren soll, wenn ihn kein Mensch inhaltlich geprüft hat oder keine Person oder Einrichtung öffentlich die redaktionelle Verantwortung übernimmt?',
      yes: 'Dann verlangt Art. 50 der KI-Verordnung einen sichtbaren Hinweis direkt am Inhalt, spätestens beim ersten Kontakt – bei Video am Anfang, bei Ton gesprochen. Dafür gibt es die EU-Kennzeichen. Das AI-DTL kann als zweite Ebene dahinter stehen. Passend wäre vermutlich: {icon}. Dies ist keine Rechtsberatung.',
      link: 'Zu den EU-Kennzeichen',
      no: 'Dann ist das AI-DTL eine freiwillige Angabe.',
      unknown: 'Im Zweifel lieber zusätzlich kennzeichnen. Fragen Sie Ihre zuständige Stelle.',
      icons: { partial: 'Partially AI-Modified', full: 'Fully AI-Generated', basic: 'Basis-Icon mit kurzem Textzusatz' },
    },
    missing: {
      title: 'Es fehlt noch: {list}',
      stamm: 'Was hat die KI gemacht?',
      tool: 'Werkzeug',
      date: 'Monat der letzten Nutzung',
      host: 'Rechner',
      review: 'Prüfung',
      acc: 'Verantwortung',
    },
    page: {
      invalid: 'Ungültiges Label',
      invalid_sub: 'Die URL enthält kein gültiges AI-DTL-Label. Bitte verwenden Sie den Editor.',
      code: 'Code',
      tools: 'Werkzeuge',
      not_says_title: 'Was dieses Label nicht sagt',
      not_says: 'Das Label ist eine Selbstauskunft der Erstellenden. Es sagt nichts darüber, ob der Inhalt richtig ist, und es ersetzt keine technische Herkunftsprüfung. Wo die KI-Verordnung eine Kennzeichnung verlangt, ersetzt es auch nicht das EU-Kennzeichen.',
      eu_title: 'Verhältnis zum EU-Kennzeichen',
      eu: 'Das EU-Kennzeichen steht direkt am Inhalt und sagt: Hier war KI beteiligt. Das AI-DTL kann die zweite Ebene dahinter sein und sagt, wie: was die KI gemacht hat, wo sie lief, wer geprüft hat und wer einsteht.',
      legacy04: 'Dieses Label folgt der älteren Version 0.4. Einige Begriffe sind seitdem genauer gefasst, siehe Changelog.',
      create_own: 'Eigenes Label erstellen',
    },
    badge: {
      N: 'ohne KI', A: 'nur Form', S: 'Prozesshilfe', M: 'KI-verändert', G: 'KI-erzeugt',
      'H:L': 'lokal', 'H:I': 'Hochschulrechner', 'H:C': 'mit Vertrag', 'H:C!': 'ohne Vertrag',
      'R:H': 'Mensch prüfte', 'R:HM': 'Mensch + Software', 'R:M': 'nur Software', 'R:N': 'ungeprüft',
      'Acc:I': 'Person', 'Acc:O': 'Organisation', 'Acc:N': 'niemand',
    },
  };

  const en = {
    ui: {
      title: 'AI-DTL – Disclose AI use',
      subtitle: 'Five steps to a label made of a plain-language sentence and a code.',
      header_version: 'v 0.5 (preview)',
      skip: 'Skip to the editor',
      step: 'Step',
      doi: 'DOI to follow (Zenodo)',
      downloaded: 'Downloaded',
      multi: 'Multiple selection possible',
      single: 'Choose one',
      restart: 'Start over',
      example: 'Load example',
      example_none: '– choose an example –',
      yes: 'Yes', no: 'No', dont_know: 'Don’t know',
      result_title: 'Your AI-DTL',
      copied: 'Copied',
      remove_tool: 'Remove tool',
      tool_name: 'Tool',
      month: 'Month', year: 'Year',
      when_title: 'When does the editor show hints?',
      btn_text: 'Text', btn_html: 'HTML snippet', btn_md: 'Markdown', btn_latex: 'LaTeX',
      btn_link: 'Link', btn_speech: 'Spoken text', btn_svg: 'Badge ↓ SVG', btn_png: 'Badge ↓ PNG',
      study_banner: 'Study mode – your input is not stored',
      study_case: 'Case',
      study_copy: 'Copy result for the questionnaire',
      footer_test: 'Version 0.5 is currently being tested with users – feedback welcome',
      legacy_loaded: 'This label was created with version 0.4. Please check it against the 0.5 rules.',
      part_label: 'Only a single image, video or audio clip was generated or modified with AI? Recommended: a separate label directly on that element and one label for the rest of the work.',
    },
    months: SPEC_04.i18n.en.months,
    steps: {
      stamm:  { title: 'What did the AI do?', sub: 'Select all that apply. The label shows the strongest level.' },
      tools:  { title: 'Which AI tools did you use?', sub: 'Name of the service and, if known, the model, plus the month you last used it for this work.' },
      host:   { title: 'Whose computers did the AI run on?', sub: 'What matters is where your input was processed – not who developed the model.' },
      review: { title: 'Was the AI output reviewed?', sub: '' },
      acc:    { title: 'Who is accountable for the work?', sub: 'Machines can check, but cannot be accountable.' },
    },
    opt: {
      N: { lbl: 'No AI', dsc: 'Created without AI. Built-in spell-checking does not count.' },
      A: { lbl: 'Language and form', dsc: 'AI only corrected errors or smoothed single sentences, translated or transcribed your own material, or improved image quality. Wording and depiction are essentially yours.' },
      S: { lbl: 'Help in the process', dsc: 'AI helped with ideas, structure, research, feedback or debugging. The finished work contains no AI content.' },
      M: { lbl: 'Existing work modified', dsc: 'AI reworked your existing work beyond single sentences: rephrased paragraphs, changed code (fix, refactoring), edited what a photo shows (removed objects, replaced background), altered a voice or face in a recording.' },
      G: enableM
        ? { lbl: 'Newly generated', dsc: 'AI generated content that appears in the work: text, summary, code, data, image, audio or video – also from your material and even if you revised it afterwards.' }
        : { lbl: 'AI content in the work', dsc: 'AI generated content that appears in the work: text, summary, code, data, image, audio or video – also from your material and even if you revised it afterwards – or modified existing work: rephrased paragraphs, changed code, edited a photo, altered a voice.' },
      'H:L':  { lbl: 'Own device', dsc: 'On your computer (including your work computer) or a server under your own control, e.g. with Ollama. Nothing sent to third parties.' },
      'H:I':  { lbl: 'Research institution', dsc: 'In the data centre of a university or public research institution, e.g. open models in the Academic Cloud (GWDG).' },
      'H:C':  { lbl: 'Provider with contract', dsc: 'At a commercial provider under a contract with your institution that forbids it to use your input for its own purposes (e.g. training), e.g. Microsoft 365 Copilot with a university licence.' },
      'H:C!': { lbl: 'Provider without contract', dsc: 'At a commercial provider without such a contract, e.g. a private or free account.' },
      'R:H':  { lbl: 'By a human', dsc: 'A person checked the substance, not just the form – facts, sources, claims – after the last AI change.' },
      'R:HM': { lbl: 'Human and software', dsc: 'As above, plus automated checks (e.g. tests, linters).' },
      'R:M':  { lbl: 'Software only', dsc: 'Automated checks only. This does not count as human review.' },
      'R:N':  { lbl: 'Not reviewed', dsc: 'AI output was adopted without review.' },
      'Acc:I': { lbl: 'A person', dsc: 'You or another named person, e.g. the author.' },
      'Acc:O': { lbl: 'An organisation', dsc: 'The body in whose name it is published, e.g. university, office, editorial team.' },
      'Acc:N': { lbl: 'No one', dsc: 'Neither a person nor an organisation takes responsibility. Rare in universities.' },
    },
    cumul: {
      stamm: 'In the label: {X} – if several apply, the strongest counts.',
      host: 'In the label: {X} – if several apply, the least protected location counts.',
    },
    helper: {
      title: 'Not sure? A few questions',
      q1: 'Does the finished work contain anything the AI generated or changed – even just a correction?',
      q1b: 'Did AI help you with ideas, structure, research or debugging?',
      q2: 'Did the AI only correct errors or smooth single sentences, translate or transcribe your own material, or improve image quality?',
      q2b: 'Did AI also help with ideas, structure, research or debugging?',
      q3: 'Has your own work been preserved and changed by the AI beyond single sentences (e.g. rephrased paragraphs, changed code, an object removed from a photo)? → M. Or did the AI produce something new, even from your material (e.g. summary, text from bullet points, new function, image, synthetic voice)? → G.',
      q3_both: 'Both',
      both_note: 'If both occur (modified and newly generated), G applies.',
      result: 'Suggestion: {X}',
      apply: 'Apply',
      again: 'Start again',
    },
    purpose: {
      label: 'What was AI used for? (optional)',
      ph: 'e.g. translating the summary, image on slide 12',
      help: 'Appears only in the sentence, not in the code.',
    },
    no_ai_hint: 'Without AI, the steps on tools, hosting and review are skipped.',
    tools: {
      ph: 'e.g. Academic Cloud/Llama 3.3 70B',
      date: 'Month of last use',
      add: '+ add tool',
      generic: 'Tip: add the model or version after the slash, e.g. “ChatGPT/GPT-5”.',
      host_suggest: 'Suggested for the next step: {host}, because you chose “{service}”. Please check.',
      bad_chars: 'The characters ; ( ) , | cannot be used in tool names.',
    },
    host_hint: 'A university licence does not mean university servers: licensed services usually run at the provider (provider with contract).',
    review_hint_as: 'For “Language and form” or “Help in the process”: did you consciously accept or reject the AI’s suggestions? Then choose “By a human”.',
    resp: {
      label: 'Who is accountable? (optional)',
      ph: 'e.g. Dr Maria Muster or Office of Communications',
      help: 'Name or institution. You can add an ORCID or ROR ID; it will be linked. Appears only in the sentence.',
    },
    sentence: {
      stamm: {
        N: 'Created without AI.',
        A: 'Content by humans; AI only helped with language or form.',
        S: 'Content by humans; AI helped in the working process.',
        M: 'Contains content modified with AI.',
        G: 'Contains content generated with AI.',
      },
      purpose: 'AI used for: {p}.',
      reviewAS: {
        'R:H': 'AI suggestions reviewed by a human.',
        'R:HM': 'AI suggestions reviewed by a human and automatically.',
        'R:M': 'AI suggestions checked automatically only.',
        'R:N': 'AI suggestions used without review.',
      },
      reviewMG: {
        'R:H': 'AI output reviewed for substance by a human.',
        'R:HM': 'AI output reviewed for substance by a human and also checked automatically.',
        'R:M': 'AI output checked automatically only, not by a human.',
        'R:N': 'AI output not reviewed.',
      },
      resp: 'Accountable: {rp}.',
      acc: {
        'Acc:I': 'A person takes responsibility.',
        'Acc:O': 'An organisation takes responsibility.',
        'Acc:N': 'No one takes responsibility.',
      },
      tool: 'Tool: {list}.',
      tools: 'Tools: {list}.',
    },
    speech: {
      prefix: 'Note:',
      stamm: {
        N: 'This content was created without AI.',
        A: 'This content is by humans; AI only helped with language or form.',
        S: 'This content is by humans; AI helped in the working process.',
        M: 'This content was modified with AI.',
        G: 'This content was generated with AI.',
      },
      review: {
        'R:H': 'A person reviewed it.',
        'R:HM': 'A person and software reviewed it.',
        'R:M': 'It was checked automatically only.',
        'R:N': 'It was not reviewed.',
      },
    },
    warn: {
      hcx: 'You used a service without a contract. Did you enter personal or confidential data? That is usually not permitted.',
      mg_rn: 'AI content was adopted without review. Check facts and sources before publishing.',
      mg_rm: 'Automated checks alone do not replace human review.',
      accn: 'No one takes responsibility. Would “An organisation” fit better?',
    },
    art50: {
      title: 'Does the content also need the EU label?',
      question: 'Will the content be published and is it (a) a realistic image, audio or video showing or altering real people, places or events, or (b) a text meant to inform the public on matters of public interest that no human reviewed for substance or for which no person or body publicly takes editorial responsibility?',
      yes: 'Then Art. 50 of the AI Act requires a visible notice directly on the content, at the latest at first contact – at the start of a video, spoken for audio. The EU labels exist for this. The AI-DTL can sit behind it as a second layer. Likely fitting: {icon}. This is not legal advice.',
      link: 'To the EU labels',
      no: 'Then the AI-DTL is a voluntary statement.',
      unknown: 'If in doubt, label additionally. Ask the office responsible.',
      icons: { partial: 'Partially AI-Modified', full: 'Fully AI-Generated', basic: 'basic icon with a short text addition' },
    },
    missing: {
      title: 'Still missing: {list}',
      stamm: 'What did the AI do?',
      tool: 'Tool',
      date: 'Month of last use',
      host: 'Hosting',
      review: 'Review',
      acc: 'Accountability',
    },
    page: {
      invalid: 'Invalid label',
      invalid_sub: 'This URL does not contain a valid AI-DTL label. Please use the editor.',
      code: 'Code',
      tools: 'Tools',
      not_says_title: 'What this label does not say',
      not_says: 'The label is a self-declaration by its creators. It says nothing about whether the content is correct, and it does not replace technical provenance checks. Where the AI Act requires labelling, it does not replace the EU label either.',
      eu_title: 'Relation to the EU label',
      eu: 'The EU label sits directly on the content and says: AI was involved here. The AI-DTL can be the second layer behind it and says how: what the AI did, where it ran, who reviewed it and who is accountable.',
      legacy04: 'This label follows the older version 0.4. Some terms have since been defined more precisely, see the changelog.',
      create_own: 'Create your own label',
    },
    badge: {
      N: 'no AI', A: 'form only', S: 'process aid', M: 'AI-modified', G: 'AI-generated',
      'H:L': 'local', 'H:I': 'univ. servers', 'H:C': 'with contract', 'H:C!': 'no contract',
      'R:H': 'human review', 'R:HM': 'human + software', 'R:M': 'software only', 'R:N': 'unreviewed',
      'Acc:I': 'person', 'Acc:O': 'organisation', 'Acc:N': 'no one',
    },
  };

  if (!enableM) {
    [de, en].forEach(t => {
      delete t.opt.M; delete t.sentence.stamm.M; delete t.speech.stamm.M; delete t.badge.M;
      delete t.helper.q3; delete t.helper.q3_both; delete t.helper.both_note;
    });
  }

  return {
    version: '0.5',
    enableM,
    codes: {
      stamm:  stammRank,
      host:   { 'H:C!': 0, 'H:C': 1, 'H:I': 2, 'H:L': 3 },
      review: { 'R:H': 0, 'R:HM': 1, 'R:M': 2, 'R:N': 3 },
      acc:    { 'Acc:I': 0, 'Acc:O': 1, 'Acc:N': 2 },
    },
    order: {
      stamm:  stammOrder,
      host:   ['H:L', 'H:I', 'H:C', 'H:C!'],
      review: ['R:H', 'R:HM', 'R:M', 'R:N'],
      acc:    ['Acc:I', 'Acc:O', 'Acc:N'],
    },
    rules: {
      noAiAcc: ['Acc:I', 'Acc:O'],
      noAiAccLegacy: ['Acc:I', 'Acc:O'],
      toolRequired: true,
      dateRequired: true,
      toolNameMax: 80,
      freeTextMax: 120,
    },
    warnings: [
      { id: 'hcx',   trigger: 'H:C!',        when: s => s.host === 'H:C!' },
      { id: 'mg_rn', trigger: enableM ? 'M/G + R:N' : 'G + R:N', when: s => mg(s) && s.review === 'R:N' },
      { id: 'mg_rm', trigger: enableM ? 'M/G + R:M' : 'G + R:M', when: s => mg(s) && s.review === 'R:M' },
      { id: 'accn',  trigger: 'Acc:N',       when: s => s.acc === 'Acc:N' },
    ],
    euLabelsUrl: 'https://digital-strategy.ec.europa.eu/en/policies/eu-icons-labelling-ai-generated-content',
    i18n: { de, en },
  };
}

const SPEC = {
  '0.4': deepFreeze(SPEC_04),
  '0.5': deepFreeze(buildSpec05(ENABLE_M)),
};

if (typeof module !== 'undefined') {
  module.exports = { SITE_BASE, ENABLE_M, SPEC, buildSpec05: m => deepFreeze(buildSpec05(m)) };
}
